[project]
name = "bird-watching"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = []

[build-system]
requires= ["hatchling"]
build-backend = "hatchling.build"

[project.optional-dependencies]
ingestion = ["pandas", "requests", "pydantic-ai", "python-dotenv"]
dev = ["pytest", "requests-mock"]

[tool.pytest.ini_options]
testpaths = ["tests"]

[tool.hatch.build.targets.wheel]
packages = ["src/bird_watching"]